CONTRIBUTING.md, EnyimMemcached/NHibernate.Caches.EnyimMemcached/MemCacheClient.cs, MemCache/NHibernate.Caches.MemCache/MemCacheClient.cs, NHibernate.Caches.Common.Tests/Async/CacheFixture.cs, NHibernate.Caches.Common.Tests/CacheFixture.cs
[NHCH-43](https://nhibernate.jira.com/browse/NHCH-43)
=> NHCH-43 - Fix unicode key collisions

NHibernate.Caches.Common.Tests/Async/CacheFixture.cs, NHibernate.Caches.Common.Tests/CacheFixture.cs, SysCache2/NHibernate.Caches.SysCache2.Tests/SysCacheFixture.cs, SysCache2/NHibernate.Caches.SysCache2/SysCacheRegion.cs
[NHCH-52](https://nhibernate.jira.com/browse/NHCH-52).
=> NHCH-52 - Default configurable expiration for SysCache2

RtMemoryCache/NHibernate.Caches.RtMemoryCache.Tests/App.config, RtMemoryCache/NHibernate.Caches.RtMemoryCache.Tests/RtMemoryCacheFixture.cs, RtMemoryCache/NHibernate.Caches.RtMemoryCache.Tests/RtMemoryCacheProviderFixture.cs, RtMemoryCache/NHibernate.Caches.RtMemoryCache.Tests/RtMemoryCacheSectionHandlerFixture.cs, RtMemoryCache/NHibernate.Caches.RtMemoryCache/CacheConfig.cs, RtMemoryCache/NHibernate.Caches.RtMemoryCache/RtMemoryCache.cs, RtMemoryCache/NHibernate.Caches.RtMemoryCache/RtMemoryCacheSectionHandler.cs
[NHCH-53](https://nhibernate.jira.com/browse/NHCH-53)
=> NHCH-53 - Remove pointless priority handling from RtMemoryCache

EnyimMemcached/NHibernate.Caches.EnyimMemcached.Tests/Async/MemCacheFixture.cs, MemCache/NHibernate.Caches.MemCache.Tests/Async/MemCacheFixture.cs, NHibernate.Caches.Common.Tests/Async/CacheFixture.cs, NHibernate.Caches.Common.Tests/CacheProviderFixture.cs, RtMemoryCache/NHibernate.Caches.RtMemoryCache.Tests/App.config, RtMemoryCache/NHibernate.Caches.RtMemoryCache.Tests/RtMemoryCacheProviderFixture.cs, RtMemoryCache/NHibernate.Caches.RtMemoryCache.Tests/RtMemoryCacheSectionHandlerFixture.cs, RtMemoryCache/NHibernate.Caches.RtMemoryCache/RtMemoryCache.cs, RtMemoryCache/NHibernate.Caches.RtMemoryCache/RtMemoryCacheProvider.cs, RtMemoryCache/NHibernate.Caches.RtMemoryCache/RtMemoryCacheSectionHandler.cs, SysCache/NHibernate.Caches.SysCache.Tests/App.config, SysCache/NHibernate.Caches.SysCache.Tests/SysCacheProviderFixture.cs, SysCache/NHibernate.Caches.SysCache/SysCache.cs, SysCache/NHibernate.Caches.SysCache/SysCacheProvider.cs, SysCache2/NHibernate.Caches.SysCache2.Tests/App.config, SysCache2/NHibernate.Caches.SysCache2.Tests/SysCacheProviderFixture.cs, SysCache2/NHibernate.Caches.SysCache2.Tests/SysCacheSectionFixture.cs, SysCache2/NHibernate.Caches.SysCache2/SysCacheProvider.cs, SysCache2/NHibernate.Caches.SysCache2/SysCacheRegion.cs, Tools/packages.config
=> Fix partially configured regions not fallback-ing on defauts

SysCache2/NHibernate.Caches.SysCache2/SysCacheProvider.cs
=> Modernize concurrency handling in SysCache2

CoreMemoryCache/NHibernate.Caches.CoreMemoryCache.Tests/CoreMemoryCacheSectionHandlerFixture.cs, CoreMemoryCache/NHibernate.Caches.CoreMemoryCache/CacheConfig.cs, CoreMemoryCache/NHibernate.Caches.CoreMemoryCache/CoreMemoryCacheProvider.cs, CoreMemoryCache/NHibernate.Caches.CoreMemoryCache/CoreMemoryCacheSectionHandler.cs
Fix errors in xml comments, refactor the configuration logic and test it
more thoroughly.
=> Refine .Net Core Memory cache

CoreMemoryCache/default.build, EnyimMemcached/default.build, MemCache/NHibernate.Caches.MemCache/NHibernate.Caches.MemCache.csproj, MemCache/default.build, Prevalence/NHibernate.Caches.Prevalence/NHibernate.Caches.Prevalence.csproj, Prevalence/default.build, RtMemoryCache/default.build, SharedCache/NHibernate.Caches.SharedCache/NHibernate.Caches.SharedCache.csproj, SharedCache/default.build, SysCache/default.build, SysCache2/default.build, Velocity/NHibernate.Caches.Velocity/NHibernate.Caches.Velocity.csproj, Velocity/default.build, appveyor.yml, buildcommon.xml, default.build
This build NuGet packages and the binary zip. Each NuGet package is downloadable individually, but also a package zip containing them all along with a publish script is available.
=> Build release artifacts on AppVeyor

RtMemoryCache/NHibernate.Caches.RtMemoryCache.Tests/NHibernate.Caches.RtMemoryCache.Tests.csproj, RtMemoryCache/NHibernate.Caches.RtMemoryCache.Tests/Program.cs, RtMemoryCache/NHibernate.Caches.RtMemoryCache.Tests/RtMemoryCacheFixture.cs, RtMemoryCache/NHibernate.Caches.RtMemoryCache.Tests/RtMemoryCacheProviderFixture.cs, RtMemoryCache/NHibernate.Caches.RtMemoryCache.Tests/TestsContext.cs, RtMemoryCache/NHibernate.Caches.RtMemoryCache/NHibernate.Caches.RtMemoryCache.csproj, RtMemoryCache/default.build, appveyor.yml, readme.md
=> Add .NET Standard 2.0 target to RtMemoryCache

StackExchangeRedis/NHibernate.Caches.StackExchangeRedis/Lua/DefaultRegionStrategy/LockMany.lua
The current script works as lua is able to compare different types, but it is better to use the same types.
=> Fix StackExchangeRedis LockMany script for DefaultRegionStrategy

StackExchangeRedis/NHibernate.Caches.StackExchangeRedis/Lua/FastRegionStrategy/SlidingGetMany.lua
=> Fix StackExchangeRedis GetMany with expiration lua script for FastRegionStrategy

StackExchangeRedis/NHibernate.Caches.StackExchangeRedis.Tests/Providers/DistributedRedisCacheProvider.cs, StackExchangeRedis/NHibernate.Caches.StackExchangeRedis/RedisCacheProvider.cs
=> Fix for Custom Regions with RedisCacheProvider

CoreDistributedCache/NHibernate.Caches.CoreDistributedCache/CoreDistributedCacheProvider.cs, CoreMemoryCache/NHibernate.Caches.CoreMemoryCache/CoreMemoryCacheProvider.cs, RtMemoryCache/NHibernate.Caches.RtMemoryCache/RtMemoryCacheProvider.cs, StackExchangeRedis/NHibernate.Caches.StackExchangeRedis/RedisCacheProvider.cs, SysCache/NHibernate.Caches.SysCache/SysCacheProvider.cs, SysCache2/NHibernate.Caches.SysCache2/SysCacheProvider.cs
Requested [in comment](https://github.com/nhibernate/NHibernate-Caches/pull/67#discussion_r275792226).
=> Add static region configuration

CoreDistributedCache/NHibernate.Caches.CoreDistributedCache.Redis/NHibernate.Caches.CoreDistributedCache.Redis.csproj, CoreDistributedCache/NHibernate.Caches.CoreDistributedCache/NHibernate.Caches.CoreDistributedCache.csproj, CoreMemoryCache/NHibernate.Caches.CoreMemoryCache/NHibernate.Caches.CoreMemoryCache.csproj, NHibernate.Caches.Common/NHibernate.Caches.Common.csproj, NHibernate.Caches.props, RtMemoryCache/NHibernate.Caches.RtMemoryCache/NHibernate.Caches.RtMemoryCache.csproj, StackExchangeRedis/NHibernate.Caches.StackExchangeRedis/NHibernate.Caches.StackExchangeRedis.csproj, SysCache/NHibernate.Caches.SysCache/NHibernate.Caches.SysCache.csproj, SysCache2/NHibernate.Caches.SysCache2/NHibernate.Caches.SysCache2.csproj, appveyor.yml, buildcommon.xml, readme.md
It seems to me it is about time for a release.
=> Release v5.6

CoreDistributedCache/NHibernate.Caches.CoreDistributedCache.Memcached/NHibernate.Caches.CoreDistributedCache.Memcached.csproj, CoreDistributedCache/NHibernate.Caches.CoreDistributedCache.Memory/NHibernate.Caches.CoreDistributedCache.Memory.csproj, CoreDistributedCache/NHibernate.Caches.CoreDistributedCache.Redis/NHibernate.Caches.CoreDistributedCache.Redis.csproj, CoreDistributedCache/NHibernate.Caches.CoreDistributedCache.SqlServer/NHibernate.Caches.CoreDistributedCache.SqlServer.csproj, CoreDistributedCache/NHibernate.Caches.CoreDistributedCache.Tests/App.config, CoreDistributedCache/NHibernate.Caches.CoreDistributedCache.Tests/CoreDistributedCacheProviderFixture.cs, CoreDistributedCache/NHibernate.Caches.CoreDistributedCache.Tests/CoreDistributedCacheSectionHandlerFixture.cs, CoreDistributedCache/NHibernate.Caches.CoreDistributedCache.Tests/TestSerializer1.cs, CoreDistributedCache/NHibernate.Caches.CoreDistributedCache.Tests/TestSerializer2.cs, CoreDistributedCache/NHibernate.Caches.CoreDistributedCache/Async/CoreDistributedCache.cs, CoreDistributedCache/NHibernate.Caches.CoreDistributedCache/CacheConfig.cs, CoreDistributedCache/NHibernate.Caches.CoreDistributedCache/CoreDistributedCache.cs, CoreDistributedCache/NHibernate.Caches.CoreDistributedCache/CoreDistributedCacheProvider.cs, CoreDistributedCache/NHibernate.Caches.CoreDistributedCache/CoreDistributedCacheSectionHandler.cs, CoreDistributedCache/NHibernate.Caches.CoreDistributedCache/NHibernate.Caches.CoreDistributedCache.csproj, NHibernate.Caches.Common/BinaryCacheSerializer.cs, NHibernate.Caches.Common/NHibernate.Caches.Common.csproj, readme.md
=> Allow serializer customization

CoreDistributedCache/NHibernate.Caches.CoreDistributedCache.Memcached/NHibernate.Caches.CoreDistributedCache.Memcached.csproj, CoreDistributedCache/NHibernate.Caches.CoreDistributedCache.Memory/NHibernate.Caches.CoreDistributedCache.Memory.csproj, CoreDistributedCache/NHibernate.Caches.CoreDistributedCache.Redis/NHibernate.Caches.CoreDistributedCache.Redis.csproj, CoreDistributedCache/NHibernate.Caches.CoreDistributedCache.SqlServer/NHibernate.Caches.CoreDistributedCache.SqlServer.csproj, CoreDistributedCache/NHibernate.Caches.CoreDistributedCache.Tests/CoreDistributedCacheSectionHandlerFixture.cs, CoreDistributedCache/NHibernate.Caches.CoreDistributedCache/ConfigurationProvider.cs, CoreDistributedCache/NHibernate.Caches.CoreDistributedCache/CoreDistributedCacheProvider.cs, CoreDistributedCache/NHibernate.Caches.CoreDistributedCache/CoreDistributedCacheSectionHandler.cs, CoreDistributedCache/NHibernate.Caches.CoreDistributedCache/NHibernate.Caches.CoreDistributedCache.csproj, CoreMemoryCache/NHibernate.Caches.CoreMemoryCache/ConfigurationProvider.cs, CoreMemoryCache/NHibernate.Caches.CoreMemoryCache/CoreMemoryCacheProvider.cs, CoreMemoryCache/NHibernate.Caches.CoreMemoryCache/CoreMemoryCacheSectionHandler.cs, CoreMemoryCache/NHibernate.Caches.CoreMemoryCache/NHibernate.Caches.CoreMemoryCache.csproj, NHibernate.Caches.Common.Tests/TestsContextHelper.cs, NHibernate.Caches.Common/ConfigurationProviderBase.cs, NHibernate.Caches.Common/ICacheConfigurationSectionHandler.cs, NHibernate.Caches.Common/NHibernate.Caches.Common.csproj, RtMemoryCache/NHibernate.Caches.RtMemoryCache.Tests/NHibernate.Caches.RtMemoryCache.Tests.csproj, RtMemoryCache/NHibernate.Caches.RtMemoryCache.Tests/RtMemoryCacheSectionHandlerFixture.cs, RtMemoryCache/NHibernate.Caches.RtMemoryCache/ConfigurationProvider.cs, RtMemoryCache/NHibernate.Caches.RtMemoryCache/NHibernate.Caches.RtMemoryCache.csproj, RtMemoryCache/NHibernate.Caches.RtMemoryCache/RtMemoryCacheProvider.cs, RtMemoryCache/NHibernate.Caches.RtMemoryCache/RtMemoryCacheSectionHandler.cs, StackExchangeRedis/NHibernate.Caches.StackExchangeRedis.Tests/RedisSectionHandlerFixture.cs, StackExchangeRedis/NHibernate.Caches.StackExchangeRedis/ConfigurationProvider.cs, StackExchangeRedis/NHibernate.Caches.StackExchangeRedis/NHibernate.Caches.StackExchangeRedis.csproj, StackExchangeRedis/NHibernate.Caches.StackExchangeRedis/RedisCacheProvider.cs, StackExchangeRedis/NHibernate.Caches.StackExchangeRedis/RedisSectionHandler.cs
=> Allow replacing ConfigurationManager for reading config values

CoreDistributedCache/NHibernate.Caches.CoreDistributedCache.Memcached/NHibernate.Caches.CoreDistributedCache.Memcached.csproj, CoreDistributedCache/NHibernate.Caches.CoreDistributedCache.Memory/NHibernate.Caches.CoreDistributedCache.Memory.csproj, CoreDistributedCache/NHibernate.Caches.CoreDistributedCache.Redis/NHibernate.Caches.CoreDistributedCache.Redis.csproj, CoreDistributedCache/NHibernate.Caches.CoreDistributedCache.SqlServer/NHibernate.Caches.CoreDistributedCache.SqlServer.csproj, CoreDistributedCache/NHibernate.Caches.CoreDistributedCache/NHibernate.Caches.CoreDistributedCache.csproj, CoreMemoryCache/NHibernate.Caches.CoreMemoryCache/NHibernate.Caches.CoreMemoryCache.csproj, NHibernate.Caches.Common/NHibernate.Caches.Common.csproj, NHibernate.Caches.props, RtMemoryCache/NHibernate.Caches.RtMemoryCache/NHibernate.Caches.RtMemoryCache.csproj, StackExchangeRedis/NHibernate.Caches.StackExchangeRedis/NHibernate.Caches.StackExchangeRedis.csproj, appveyor.yml, buildcommon.xml, readme.md
Release 5.7.0.
I was looking into adding a SqlDependency cache for this release, but it may take me too long to have enough time for doing it soon, so I have changed my mind for publishing this now.
=> Release 5.7.0

CoreDistributedCache/NHibernate.Caches.CoreDistributedCache.Tests/Async/CoreDistributedCacheFixture.cs, CoreDistributedCache/NHibernate.Caches.CoreDistributedCache.Tests/CoreDistributedCacheFixture.cs, CoreDistributedCache/NHibernate.Caches.CoreDistributedCache.Tests/NHibernate.Caches.CoreDistributedCache.Tests.csproj, CoreDistributedCache/NHibernate.Caches.CoreDistributedCache/Async/CoreDistributedCache.cs, CoreDistributedCache/NHibernate.Caches.CoreDistributedCache/CoreDistributedCache.cs, NHibernate.Caches.Everything.sln, readme.md
=> Supports use of JsonCacheSerializer

.config/dotnet-tools.json, .github/workflows/GenerateAsyncCode.yml, AsyncGenerator.yml, StackExchangeRedis/NHibernate.Caches.StackExchangeRedis/Async/AbstractRegionStrategy.cs, StackExchangeRedis/NHibernate.Caches.StackExchangeRedis/Async/DistributedLocalCacheRegionStrategy.cs, Tools/packages.csproj, buildcommon.xml, default.build, readme.md
Copied from nhibernate/nhibernate-core#3133 and
nhibernate/nhibernate-core#2605.
=> Automatically generate async code on pull request

.github/renovate.json
=> Set Renovate to rebase PRs only when conflicted

.github/workflows/GenerateAsyncCode.yml
Copied from NHibernate commit nhibernate/nhibernate-core@c84e7152f70334b5b260253fb9e658ee530491b2.
=> Remove usage of NHIBERNATE_BOT_TOKEN
